### ISSUE TITLE
https rather than http

### ISSUE THREAD

**Issue by sreyemnayr** [punkave/uploadfs#12]
Is there a way to fetch https images from s3 rather than http?  To avoid "Mixed Content" warnings?

**Comment by boutell** [comment]
Yes, just set uploadsUrl that way.

On Wed, Apr 6, 2016 at 10:42 PM, sreyemnayr <notifications@github.com>
wrote:

> Is there a way to fetch https images from s3 rather than http? To avoid
> "Mixed Content" warnings?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/uploadfs/issues/12>
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com
