### ISSUE TITLE
s3 endpoint should be configurable

### ISSUE THREAD

**Issue by boutell** [punkave/uploadfs#6]
Right now s3.amazonaws.com is hardcoded. There are (occasionally) valid reasons to change this, such as working with an AWS clone, or using  s3-external-1.amazonaws.com to force "us east" to really be just "us east" (the exact efficacy of which is somewhat underdocumented).

**Comment by tortilaman** [comment]
I noticed this issue is still (in a sense) around. While endpoint is configurable, getURL() doesn't use it. My pull request #18 should address this. It's tested working using IBM Cloud object storage

**Comment by tortilaman** [comment]
Should this be closed @boutell?

**Comment by boutell** [comment]
Looks like it!
